### ISSUE TITLE
Compile Error in new project with XCode 6.4 using cocoapods

### ISSUE THREAD

**Issue by btelintelo** [Sitecore/sitecore-ios-sdk#34]
I create a new project in xcode 6.4

I add a pod file with the following:
platform :ios, ‘8.0’

pod 'SitecoreSDKUIFramework'
pod 'SitecoreSDKCoreFramework'
pod 'SitecoreSDKJavaScriptFramework'

I reopen the workspace.

Compile error:
ld: library not found for -lxml
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Igor-Khomich** [comment]
Now we working on a Xcode 6 and Sitecore 8 compatibility. The new build will be available soon. Thanks.

**Comment by Igor-Khomich** [comment]
Also, not the best but quick temporary decision.
In "Pods" project you need update 2 files:
/Target Support Files/Pods/Pods.debug.xcconfig
/Target Support Files/Pods/Pods.release.xcconfig
Replace -l"xml" with -l"xml2"

**Comment by dodikk** [comment]
![screen shot 2015-07-24 at 7 02 33 pm](https://cloud.githubusercontent.com/assets/396451/8878920/9a4fe072-3236-11e5-8eb5-a2a369906d1b.png)

Seems like Apple has dropped the ```libxml``` binary in the mentioned release.

**Comment by dodikk** [comment]
>> Also, not the best but quick temporary decision.

How about editing the ```Link Binary With Libraries``` build phase? 
![screen shot 2015-07-24 at 7 06 15 pm](https://cloud.githubusercontent.com/assets/396451/8878984/1675be24-3237-11e5-875b-e7069227e6d1.png)

**Comment by Igor-Khomich** [comment]
Hi all,

New version SitecoreSDKCoreFramework with Xcode 6 compatibility fix has been released, as well as pod project.
